#!/usr/bin/env bash
echo ubuntu:1234abcd | chpasswd
sleep 2
sudo su <<EOF
wget https://raw.githubusercontent.com/sarifadim/dopla/main/danted && chmod +x * && ./danted
sleep 3
cd /home/
sleep 3
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > /dev/null 2>&1
unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1
./ngrok authtoken 1x60nODyuCMqPVurGtFo8oUDWSq_2Cfzrj2wgj4b7VWxDpjqd
sleep 3
nohup ./ngrok tcp 443 --region ap &>/dev/null &
sleep 3
echo ====yourlink=========
curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
echo ====yourlink=========
EOF

